name = "handwrite-classroom"
compatibility_date = "2026-03-03"
pages_build_output_dir = "public"

[durable_objects]
bindings = [
  { name = "ROOM_DO", class_name = "RoomDurableObject", script_name = "handwrite-classroom-do" }
]
